In [1]:
import pandas as pd
import re

from pathlib import Path

In [2]:
df_regex_patterns = pd.read_excel(Path().absolute() / "data/patterns.xlsx")
df_stj = pd.read_excel(Path().absolute() / "data/text_class.xlsx")

In [3]:
df_regex_patterns

,Autor(a),Nome_variável,Expressão regular
0,Danilo,Contrato temporário,\sCONTRATO TEMPORÁRIO
1,Danilo,embargos de declaração,\d{7}\-\d{2}\.\d{4}\.\d{1}\.\d{2}\.\d{4}\s- EM...
2,Estela,agravo de instrumento,N\.\s\d{7}\-\d{2}\.\d{4}\.\d{1}\.\d{2}\.\d{4}\...
3,Estela,recurso especial,\sRECURSO ESPECIAL
4,Estela,Na Lei Distrital nº 4.266/08,\d{1}\.\d{3}\/\d{2}

patterns = []
for row in df_regex_patterns.to_dict("records"):
    patterns.append({"name":row["name"],"true_exp":row["true_exp"], "false_exp":row["false_exp"], "lower_bound":row["lower_bound"], "upper_bound":row["upper_bound"]})

new_rows = []
for row in df_stj.to_dict("records"):
    dic_aux = {}
    for dic in patterns:
        found = False
        if dic["true_exp"] and re.search(r"{}".format(dic["true_exp"]), row["texto_publicacao"][int(len(row["texto_publicacao"])*dic["lower_bound"]):int(len(row["texto_publicacao"])*dic["upper_bound"])], re.I):
            found = True
        if dic["false_exp"] and re.search(r"{}".format(dic["false_exp"]), row["texto_publicacao"][int(len(row["texto_publicacao"])*dic["lower_bound"]):int(len(row["texto_publicacao"])*dic["upper_bound"])], re.I):
            found = False
        dic_aux[dic["name"]] = 1 if found else 0
    new_rows.append(dic_aux)

In [4]:
patterns = []
for row in df_regex_patterns.to_dict("records"):
    patterns.append({"name":row["Nome_variável"],"regex":row["Expressão regular"]})

In [ ]:
new_rows = []
for row in df_stj.to_dict("records"):
    dic_aux = {}
    for dic in patterns:
        found = False
        print(r"{}".format(dic["regex"]))
        if dic["regex"] and re.search(r"{}".format(dic["regex"]), row["text"], re.I):
            found = True
        dic_aux[dic["name"]] = 1 if found else 0
    new_rows.append(dic_aux)

In [9]:
new_df = pd.DataFrame(new_rows)
new_df.to_excel(Path().absolute() / "data/resultados_regex.xlsx", index=False)

In [10]:
new_df

,Contrato temporário,embargos de declaração,agravo de instrumento,recurso especial,Na Lei Distrital nº 4.266/08
0,0,0,0,0,0
1,0,0,0,0,0
2,0,0,0,0,0
3,0,0,0,0,0
4,0,0,0,0,0
...,...,...,...,...,...
671,0,0,0,0,0
672,0,0,0,0,0
673,0,0,1,0,0
674,0,0,1,0,0
675,0,1,0,0,0